env:
  - NOT_CRAN=TRUE _R_CHECK_LENGTH_1_LOGIC2_=TRUE

language: r

r:
  - oldrel
  - release
  - devel

sudo: false

cache: packages

r_packages:
  - covr

branches:
  only:
    - master
    - development
    - rc

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE, ...=list(quiet=FALSE))'
