# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

r_packages:
  - testthat

warnings_are_errors: true


# notifications:
#   email:
#     on_success: brodie.gaslam@yahoo.com
#     on_failure: brodie.gaslam@yahoo.com
