# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

r_packages:
  - testthat
  - devtools

warnings_are_errors: true

sudo: required

script: echo "options(repos = c(CRAN='http://cran.r-project.org'))" >> ~/.Rprofile
# notifications:
#   email:
#     on_success: brodie.gaslam@yahoo.com
#     on_failure: brodie.gaslam@yahoo.com
